{{- if .Values.camundaConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: camunda-bpm-platform-config
data:
  production.yml: |
    {{- .Values.configurationFiles.production | indent 4 }}
{{- end }}
