{{- if .Values.liquibase.changelog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zgw-dre-liquibase-changelog
data:
  changelog.xml: |
    {{- .Values.configurationFiles.changelog | nindent 4 }}
{{- end }}
