name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Helm dependency repos
        run: |
          helm repo add denhaag https://gemeente-denhaag.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run lint
        run: |
          cd charts 
          helm lint generic --set name=testapp --set image.repository=thisisarepo.com --set ingress.hostname=test.denhaag.nl

      - name: 'Run chart-releaser'
        # if: github.ref_name == 'main'
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          # CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
